#!/usr/bin/env python3
"""Fail if anything under a lecture directory was not produced by publish-lecture.sh.

This repository holds only approved generated bytes. Every release must be
accompanied by the receipt that authorized it, and must match that receipt
object for object. A release with no receipt is the signature of a hand
promotion, so a missing receipt is a failure, not a skip.
"""
import hashlib, json, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
problems: list[str] = []


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


lectures = sorted(d for d in ROOT.glob("l[0-9][0-9]") if d.is_dir())
if not lectures:
    print("no lecture directories yet — nothing to verify")
    sys.exit(0)

if not (ROOT / ".nojekyll").is_file():
    problems.append(".nojekyll is missing; the `current` symlink will not be served")

for lec in lectures:
    name = lec.name
    releases, receipts = lec / "releases", lec / "receipts"
    if not releases.is_dir():
        problems.append(f"{name}: no releases/ directory")
        continue

    for rel in sorted(d for d in releases.iterdir() if d.is_dir()):
        receipt = receipts / f"{rel.name}.json"
        if not receipt.is_file():
            problems.append(
                f"{name}/releases/{rel.name}: no receipt at {name}/receipts/{rel.name}.json — "
                "a release without a receipt was not produced by publish-lecture.sh"
            )
            continue
        try:
            declared = json.loads(receipt.read_text())["artifact"]["objects"]
        except Exception as exc:
            problems.append(f"{name}/receipts/{rel.name}.json: unreadable ({exc})")
            continue

        want = {o["path"]: o for o in declared}
        have = {str(p.relative_to(rel)) for p in rel.rglob("*") if p.is_file()}
        for missing in sorted(set(want) - have):
            problems.append(f"{name}/releases/{rel.name}: {missing} is in the receipt but not published")
        for extra in sorted(have - set(want)):
            problems.append(f"{name}/releases/{rel.name}: {extra} is published but not in the receipt")
        for path in sorted(set(want) & have):
            actual = sha256(rel / path)
            if actual != want[path]["sha256"]:
                problems.append(
                    f"{name}/releases/{rel.name}: {path} does not match the receipt "
                    f"({actual[:12]} != {want[path]['sha256'][:12]})"
                )

    pointer = lec / "current"
    if not pointer.is_symlink():
        problems.append(f"{name}/current is not a symlink; the stable student URL depends on it")
    else:
        target = releases / Path(pointer.readlink()).name
        if not target.is_dir():
            problems.append(f"{name}/current points at {pointer.readlink()}, which does not exist")

ignored = subprocess.run(
    ["git", "status", "--ignored", "--porcelain"], cwd=ROOT, capture_output=True, text=True
).stdout.splitlines()
for line in ignored:
    path = line[3:].strip()
    if line.startswith("!!") and re.match(r"l\d\d/", path):
        problems.append(f"{path} is git-ignored inside a lecture directory — release bytes would be dropped silently")

if problems:
    print(f"REFUSED — {len(problems)} problem(s):\n")
    for p in problems:
        print(f"  * {p}")
    sys.exit(1)

total = sum(len(list((lec / 'releases').rglob('*'))) for lec in lectures)
print(f"OK — {len(lectures)} lecture(s) verified against their receipts")
